### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by nagyrobi** [mathoudebine/homeassistant-timebox-mini#1]
Hi!
Will you add this custom component to HACS?

**Comment by mathoudebine** [comment]
Hi, this would be a very nice feature to have.
I will do it when i have some spare time (for future reference: https://hacs.xyz/docs/publish/start )
If you want to implement these changes in a PR, feel free to do it!

**Comment by mathoudebine** [comment]
Support for HACS has now been added! You can add this repository as a custom repo on HACS and install the custom integration as stated in the README
