### ISSUE TITLE
It is possible to change pixel range for another bigger divoo?

### ISSUE THREAD

**Issue by janfajessen** [mathoudebine/homeassistant-timebox-mini#13]
Sorry this is not a problem, I want to buy one of this matrix to work with Home Assistant but there are bigger than 11x11 like 16x16 or 32x32 that have a good price from Ali. 

With your awesome integration is possible to change it with a simple changes?

For what you say about including text, you could edit the images with text or make a gif with the moving text you want.

**Comment by mathoudebine** [comment]
Hi @janfajessen 
I'm not sure if this works or not with other products.

The code of the integration can be adapted easily : i made a comment about it here https://github.com/mathoudebine/homeassistant-timebox-mini/issues/2 you can edit the code to change the size, and add custom png/gif.

But I don't know if the new products have the same Bluetooth protocol as the Timebox Mini.
Nobody has said here if it works or not with newer products

A gif with text is a good idea! I just have to find a Python library that can generate a gif from the text

**Comment by janfajessen** [comment]
Oh sorry, I don't saw this issue before.

It's a little bit hard work but the text can do with gif animator pixel by pixel
