### ISSUE TITLE
Tivoo Divoom Compatibility

### ISSUE THREAD

**Issue by Isai-dc** [mathoudebine/homeassistant-timebox-mini#2]
Could this integration possible work with the Tivoo Divoom? And if not, how could I make it work with the Tivoo?

**Comment by mathoudebine** [comment]
I notice is that the Tivoo has a 16x16 LED matrix while Timebox mini has a 11x11 matrix, so some 16x16 animations/matrices samples have to be added.
Other than that, if the Tivoo still supports the original Divoom Bluetooth protocol defined here https://github.com/derHeinz/divoom-adapter then it should work with this service. 
Please feel free to try it out with your device and let me know!

**Comment by mathoudebine** [comment]
To create some 16x16 samples for your test : https://github.com/mathoudebine/homeassistant-timebox-mini#create-your-own-picture--animation
